baseURL = "https://edouard.schweisguth.fr/"
languageCode = "en-us"
title = "Edouard Schweisguth"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[menu]
	[[menu.main]]
	name = "Home"
	identifier = "home"
	weight = 100
	url = "/"

	[[menu.main]]
	name = "Posts"
	weight = 200
	identifier = "posts"
	url = "/posts/"

	[[menu.main]]
	name = "About"
	weight = 300
	identifier = "about"
	url = "/about/"

[params]
	description = "Edouard Schweisguth"
	profilePicture = "images/longboardbackpack.resized.jpg"
	displayMode = "dark"

	[[params.socialIcons]]
	icon = "fab fa-github"
	title = "GitHub"
	url = "https://github.com/edznux"

	[[params.socialIcons]]
	icon = "fab fa-twitter"
	title = "Twitter"
	url = "https://twitter.com/edznux"

	[[params.socialIcons]]
	icon = "fab fa-keybase"
	title = "Keybase"
	url = "https://keybase.io/edznux"

[outputs]
  home = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]